praticingd

diff --git a/02_installation_script b/02_installation_script
--- a/02_installation_script
+++ b/02_installation_script
@@ -2,7 +2,17 @@
 
 ID=$(id -u)
 
-DATE=$(date)
+validate(){
+
+    if [ $1 -ne 0 ]
+    then 
+        echo "ERROR"
+        exit 1
+    else
+        echo " $2 is successful"
+    fi
+
+}
 
 if [ $ID -ne 0 ]
 then 
@@ -12,15 +22,11 @@ else
     echo "you are root user"
 fi
 
-yum install git -y
+yum install nginx -y
 
-if [ $? -ne 0 ]
-then 
-    echo "ERROR"
-    exit 1
-else
-    echo "installation is successful"
-fi
+validate $? installation_of_nginx
+
+
 
 
 
